refactor: access Ember Models via Store
miragejs/ember-cli-mirage pull request #2502
Opened 2023-08-01 10:51 UTC by Pixelik

## Refactor 

Ember 5.x only allows accessing Models via the Store

This refactoring removes the following Deprecation Warning:

<img width="747" alt="Screenshot 2023-08-01 at 13 35 12" src="https://github.com/miragejs/ember-cli-mirage/assets/1423394/34e8813f-e2b1-4412-b25e-4fd06f6b6fec">

2023-09-14 02:38 UTC, SergeAstapov commented
@Pixelik sorry for delay here, do you mind to refresh branch with latest `master` to get CI going and be green?

2023-09-14 07:50 UTC, Pixelik commented
Hello. It all looks green to me and up-to-date, ready to be merged 🤔

2023-09-15 03:37 UTC, SergeAstapov commented
> Hello. It all looks green to me and up-to-date, ready to be merged 🤔

branch of this PR is outdated and although the PR status is green, it has no jobs run in "Checks" tab.

Anyways, I've created a unit test which uses `discoverEmberDataModels` function in #641 and yes it fails for embe-date@5 scenarios.
However, the fix suggested here does not work, because `application.__container__` is `undefined`.

Hence, for `discoverEmberDataModels` function compatibility with Ember Data v5 we need a different solution.

2023-09-15 03:38 UTC, SergeAstapov requested changes
this actually does not work, see CI run https://github.com/miragejs/ember-cli-mirage/actions/runs/6193523102

2023-10-02 15:18 UTC, SergeAstapov commented
@Pixelik there is no such test in master now and this PR does not add anything.

@Pixelik please see https://github.com/miragejs/ember-cli-mirage/pull/2528/files#diff-a16b283fd8b39b8decc1f1e8824d3a777dca6c861c511f6999ace605541c8807 where test added

2023-10-02 15:19 UTC, Pixelik commented
@SergeAstapov  
Oh I see you created a separate PR with tests about this
Your unit test is not going to work because the required initializers won't run during your unit test.

2023-10-02 15:26 UTC, SergeAstapov commented
@Pixelik well, yes. but how can we guarantee that it will be present by the time `discoverEmberDataModels()` is invoked in mirage config?

2023-10-02 15:33 UTC, SergeAstapov commented
@Pixelik sounds like this needs to be documented then?

2023-10-02 15:35 UTC, Pixelik commented
Perhaps. Is it possible that someone would try to `discoverEmberDataModels()` **_not_** from within an Ember app that has already been initialized ? 🤔 Sounds weird to me but.. 🤷‍♂️

2023-10-02 15:39 UTC, Pixelik commented
But yes, documenting this sounds necessary to me now as well.

2023-10-02 16:25 UTC, cah-brian-gantzler commented
Sorry for being late to the party but I would think that autoDiscoverDataModels should be passed the store. 

In setupMirage the this.owner is passed into startMirage (so if startMirage is called outside tests, this is a required param).  https://github.com/miragejs/ember-cli-mirage/blob/master/packages/ember-cli-mirage/addon-test-support/setup-mirage.js#L23, so it will be accessible

(Quick aside, makeServer can be passed as an option on SetupMirage and passed into StartMirage)
```
import makeServer from 'app/mirage/config';

setupMirage(hooks, { makeServer });
```
then in startMirage, if one is passed, it uses it, if not looks it up. https://github.com/miragejs/ember-cli-mirage/blob/master/packages/ember-cli-mirage/addon/start-mirage.js#L21 (This look up is what was prepped in one of the initializers. I would love to see a mandate of passing it in, then could remove one of the intializers). This also has the benefit of specifying different configs for different tests if needed, or a different config for dev vs test. hence why testConfig is no longer needed. 

You could lookup the store and add it here https://github.com/miragejs/ember-cli-mirage/blob/master/packages/ember-cli-mirage/addon/start-mirage.js#L29 or add owner here and require them to look it. Either way you now have a store that you could pass into autoDiscoverDataModels which might be more straight forward and intuitive. Supports multiple stores if someone did have them, plus you dont depend on the initializer for `application.__container__.` (do you even need the initializer?)

2023-10-04 00:51 UTC, SergeAstapov commented
Thank you @cah-brian-gantzler and @Pixelik for ideas and discussion! I've landed fix in #2542

2023-10-04 00:51 UTC, closed without merging